# Generated by Django 2.2.7 on 2019-11-25 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.Artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.Album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='gender_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='music.Gender'),
        ),
        migrations.CreateModel(
            name='ArtistImage',
            fields=[
                ('image_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='music.Artist')),
            ],
        ),
    ]
