version: "2"

services:
    scrapyd:
        image: ceroic/scrapyd
        restart: always
        ports:
            - '6800:6800'
    web:
        build: .
        tty: true
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        volumes:
            - "./:/app"
        environment:
            - DJANGO_SETTINGS_MODULE=songs.settings